rotor_length_mm: 127
rotor_width_mm: 10
rotor_thickness_mm: 1
rotor_mass_g: 2.2
body_length_mm: 120
body_width_mm: 25
body_height_mm: 35
body_mass_g: 400
r_cg2px_mm: [100, 0, -50]
r_cg2nx_mm: [-100, 0, -50]
motor_lookup: 'motor_lookup.csv'
motor_time_constant_ms: 200 # time it takes for motor to reach ~2/3 its command RPM
servo_time_constant_ms: 50 # time it takes for servo to reach ~2/3 its command angle